# Generated by Django 4.1.5 on 2023-01-11 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("boards", "0002_rename_topic_thread"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="topic",
            new_name="thread",
        ),
        migrations.AlterField(
            model_name="thread",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threads",
                to="boards.board",
            ),
        ),
        migrations.AlterField(
            model_name="thread",
            name="starter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
